spring:
  application:
    name: CloudStorage
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  liquibase:
    default-schema: public
    change-log: classpath:/db/changelog/main-changelog.json


logging:
  level:
    org:
      springframework:
        security: trace

server:
  servlet:
    session:
      cookie:
        max-age: 300m
        name: SESSION
        http-only: true
        secure: true
        path: /
  data:
    redis:
      port: ${SPRING_REDIS_PORT}

cloudstorage:
  storage:
    minio:
      enabled: true
      endpoint: ${MINIO_ENDPOINT}
      user: ${MINIO_ROOT_USER}
      password: ${MINIO_ROOT_PASSWORD}
      bucket: ${MINIO_BUCKET}

